### ISSUE TITLE
SRQ line makes datasette loading not working in latest pi1541 firmware

### ISSUE THREAD

**Issue by rainisto** [hackup/Pi1541io#1]
With the latest changes in pi1541 firmware (commit that introduced 1581 support) the behaviour of SRQ line has changed which causes noise (or something) to SRQ line that breaks the datasette loading.

Maybe add jumper to schematics that can be used to disconnect SRQ line from the 7406 pin8 to iec connector. So people could disconnect the line untill the burst mode support and SRQ changes are fixed in pi1541 firmware. Currently you have to cut the trace in order to get datasette loading working again.

Tested with V1.10 where datasette loaded programs fine vs v1.15 where datasette failed to load programs successfully. Steve is planning to look if there is a bug in burst mode code that might cause datasette to fail, so hopefully we also get firmware fix at some point.

**Comment by hackup** [comment]
Thanks for the report. A way to disconnect the SRQ line from the 7406 sounds like a very reasonable idea to me and I will consider that for the next revision of the board. I might just add yet another solder bridge to the bottom side.

**Comment by rainisto** [comment]
Latest commit in pi1541 has a fix: https://github.com/pi1541/Pi1541/commit/db692407c3a3afec76ae17b1bd42b1672cbd00cd

So issue goes away on next firmware version.
