### ISSUE TITLE
Add 2 extra holes for Lumberg IEC connector

### ISSUE THREAD

**Issue by fruitCoder123** [hackup/Pi1541io#3]
When you make a new board revision maybe you can consider to add 2 extra holes (the ones most to the edge of the board) to fit also the Lumberg 0105 06 connector. The 2 pins of that connector are slightly more close to the center and therfor don't fit on the current revision 5 (and lower) boards.
As the connectors are somewhat hard to get Farnell is selling the Lumberg ones, here is a reference to the farnell page where you can also find the datasheet which holds exact info about the pinning layout:
https://nl.farnell.com/lumberg/0105-06/din-connector-rcpt-6pos-chassis/dp/2677786

Thanks for your effort! I hope you like my feedback/contribution. BR

**Comment by hackup** [comment]
I think you might be mistaken. I actually added those two additional through-hole pads for the Lumberg connector in rev.5. I don't have any of those connectors though, so I never had the chance to verify the layout. 
![grafik](https://user-images.githubusercontent.com/1225249/97091307-559a7700-163b-11eb-86a9-b070d7626419.png)

See also here:
https://www.pcbway.com/project/shareproject/Pi1541_IO_Adapter__Rev_5.html

**Comment by fruitCoder123** [comment]
Allight! Somehow I took the files for version 4 as it seems, bummer! Maybe because at the main page version 5 is not mentioned..
Thanks for your effort, for now I had to snip off those 2 pins, I liked to use them as it provides a better mechanical connection but.. yeahhh...
Keep up the good work!

Please cancel this ticket

**Comment by hackup** [comment]
Thanks! Fixed in ef5f29bfcea6542e7d95b61bb5cffca7b2ee1284.
