### ISSUE TITLE
OLED display error

### ISSUE THREAD

**Issue by Banabas** [hackup/Pi1541io#5]
![IMG_20240209_110838](https://github.com/hackup/Pi1541io/assets/53483766/7fdb1494-ceba-4d59-acde-4b6da1a16a3e)
Hello.
First of all, thank you for the good project.
I have ordered io rev5 pcb's.
I now have a problem with the OLED display.
Something is cut off on the left and faded in again on the right.
The display should be OK.
Can you say something about it?

Greetings from DE

**Comment by cgraefe** [comment]
Haven't seen this before, but I did a quick search on the web. Your display probably doesn't have an SSD1306 controller which, is the default for the Pi1541 firmware. Maybe your controller is an SH1106.  If I recall correctly, there is a configuration to enable to correct driver for this one. But the firmware is not my project, an I'm not expert on that topic.

**Comment by hackup** [comment]
Haven't seen this before, but I did a quick search on the web. Your display probably doesn't have an SSD1306 controller which, is the default for the Pi1541 firmware. Maybe your controller is an SH1106. If I recall correctly, there is a configuration to enable to correct driver for this one. But the firmware is not my project, an I'm not expert on that topic.

**Comment by Banabas** [comment]
OMG why didn't I think of that?
Sorry.
I actually thought I had chosen the right display.
Guess I didn't.
It works as it should now.
Thanks again.

**Comment by hackup** [comment]
No problem. Glad to hear that you got it working now!
